version: "3.7"

services:
  traefik-errorserver:
    image: traefik-errorserver:latest
    container_name: traefik-errorserver
    restart: unless-stopped
    networks:
      # replace proxy with the network over which Traefik communicates with other containers.
      - proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.error-router.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-router.priority=1"
      - "traefik.http.routers.error-router.entrypoints=http" # <== Replace `http` with whatever you :80 entrypoint name is.
      - "traefik.http.routers.error-router.middlewares=error-pages-middleware"

      - "traefik.http.routers.error-router-secure.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.error-router-secure.entrypoints=https" # <== Replace `https` with whatever you :443 entrypoint name is.
      - "traefik.http.routers.error-router-secure.priority=1"
      - "traefik.http.routers.error-router-secure.tls=true"
      - "traefik.http.routers.error-router-secure.middlewares=error-pages-middleware"

      - "traefik.http.middlewares.error-pages-middleware.errors.status=400-599"
      - "traefik.http.middlewares.error-pages-middleware.errors.service=error-pages-service"
      - "traefik.http.middlewares.error-pages-middleware.errors.query=/{status}.html"

      - "traefik.http.services.error-pages-service.loadbalancer.server.port=80"

networks:
  # Replace proxy with the network you specified above
  proxy:
    external: true